<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="A site detailing my portfolio of Work.">
	<meta name="author" content="Himanshu Singh_aesefasiljdfbaweojg">
	<meta name="generator" content="Hugo 0.74.3" />
	<title>IMDB ratings: Differences between directors &middot; Portfolio website for Himanshu Singh</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong>Himanshu Singh</strong> <span></span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/projects">projects</a></li>
            
                <li><a href="/blogs/ipsum">Generic Blog</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/projects" class="button special fit">Get Started</a></li>
            
            
                <li><a href="/" class="button fit"></a></li>
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>IMDB ratings: Differences between directors</h1>
                            </header>
                            
                                <span class="image main"><img src="/img/blogs/imdb.png" alt="" /></span>
                            
                            


<div id="imdb-ratings-a-primer" class="section level3">
<h3>IMDB Ratings: A primer</h3>
<p>INSERT some details about the dataset</p>
</div>
<div id="the-data" class="section level3">
<h3>The Data</h3>
<p>Here is the dataset we will be working with. We can use <code>glimpse</code> to get a brief overview of the data.</p>
<pre class="r"><code>#contents of the movies dataset 
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Ave...
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;...
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevor...
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015,...
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93...
## $ gross               &lt;dbl&gt; 760505847, 658672302, 652177271, 623279547, 533...
## $ budget              &lt;dbl&gt; 237000000, 200000000, 150000000, 220000000, 185...
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, ...
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658...
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752,...
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7....</code></pre>
As we can see the <code>movies</code> is a tibble with 2,961 rows and 11 columnswhere each row refers to a specific movie, and the comluns contain more information about the movie including:
<ul>
<ul>
<li><code>duration</code> is the duration of the movie in minutes</li>
<li><code>gross</code> is the box office gross of the movies in US$</li>
<li><code>votes</code> is the number of people voted</li>
<li><code>reviews</code> is the number of reviews submitted for the movie</li>
<li><code>rating</code> is the average rating of the movie between 0 and 10</li>
<li><code>cast_facebook_likes</code> is the number of facebook likes of movie</li>
</ul>
</ul>
</div>
<div id="box-office-gross--what-makes-a-high-grossing-movie" class="section level3">
<h3>Box office Gross- What makes a high grossing movie?</h3>
<p>In our dataset we have over 2,961 movies with box office gross ranging from 760505847 USD to 703 USD. Let’s try to understand, from the datal, we traits to high grossing movies share.
First lets look at the distribution of the gross.</p>
<pre class="r"><code>options(scipen  = 999)
movies %&gt;%
  ggplot() + 
  geom_histogram(aes(gross), fill = &#39;white&#39; , size = 1.3) +
  labs(x = &#39;Box Office Gross USD&#39;,
       y = &#39;Count&#39;,
       title = &#39;Most moviees are average!&#39; ,
       subtitle = &#39;Distribution of Box Office Gross&#39;) +
  scale_colour_solarized(&quot;blue&quot;)+
  theme(
        plot.background = element_rect(fill = &#39;#2B304A&#39;,),
        axis.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;), 
        axis.text =  element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;) ,
        panel.grid = element_blank() ,
        panel.border = element_blank(),
        plot.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        plot.subtitle = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        panel.background = element_rect(fill = &#39;#2B304A&#39;, color = &#39;#2B304A&#39;) 
        
        )</code></pre>
<p><img src="/blogs/imdb_rat_files/figure-html/unnamed-chunk-3-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>Everyone has their own favorite genre of movie and debate In our dataset we have 17 genres,</p>
<pre class="r"><code>#list the gneres in</code></pre>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://www.twitter.com" class="icon alt fa-twitter" target="_blank"><span class="label">Twitter</span></a></li>
                
                    <li><a href="https://www.facebook.com" class="icon alt fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
                
                    <li><a href="https://www.instagram.com" class="icon alt fa-instagram" target="_blank"><span class="label">Instagram</span></a></li>
                
                    <li><a href="https://www.github.com" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="https://www.linkedin.com" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; Company Name</li>
                
                <li>Design:  <a href="https://www.html5up.net">HTML5 UP</a></li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
