---
title: 'IMDB ratings: Differences between directors'
date: '2017-10-31T21:28:43-05:00'
description: ''
draft: no
image: imdb.png
keywords: ''
slug: imdb_rat
categories:
- ''
- ''
---



<div id="imdb-ratings-a-primer" class="section level3">
<h3>IMDB Ratings: A primer</h3>
<p>INSERT some details about the dataset</p>
</div>
<div id="the-data" class="section level3">
<h3>The Data</h3>
<p>Here is the dataset we will be working with. We can use <code>glimpse</code> to get a brief overview of the data.</p>
<pre class="r"><code>#contents of the movies dataset 
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Ave...
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;...
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevor...
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015,...
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93...
## $ gross               &lt;dbl&gt; 760505847, 658672302, 652177271, 623279547, 533...
## $ budget              &lt;dbl&gt; 237000000, 200000000, 150000000, 220000000, 185...
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, ...
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658...
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752,...
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7....</code></pre>
As we can see the <code>movies</code> is a tibble with 2,961 rows and 11 columnswhere each row refers to a specific movie, and the comluns contain more information about the movie including:
<ul>
<ul>
<li><code>duration</code> is the duration of the movie in minutes</li>
<li><code>gross</code> is the box office gross of the movies in US$</li>
<li><code>votes</code> is the number of people voted</li>
<li><code>reviews</code> is the number of reviews submitted for the movie</li>
<li><code>rating</code> is the average rating of the movie between 0 and 10</li>
<li><code>cast_facebook_likes</code> is the number of facebook likes of movie</li>
</ul>
</ul>
</div>
<div id="box-office-gross--what-makes-a-high-grossing-movie" class="section level3">
<h3>Box office Gross- What makes a high grossing movie?</h3>
<p>In our dataset we have over 2,961 movies with box office gross ranging from 760505847 USD to 703 USD. Let’s try to understand, from the datal, we traits to high grossing movies share.
First lets look at the distribution of the gross.</p>
<pre class="r"><code>options(scipen  = 999)
movies %&gt;%
  ggplot() + 
  geom_histogram(aes(gross/1000000), fill = &#39;#EA8272&#39; , size = 1.3) +
  
  #adding mean line and label
  geom_vline(aes(xintercept = mean(gross/1000000)), color = &#39;#F9F871&#39; , size = 2,
                          linetype = &#39;dotted&#39;)+ 
  geom_text(aes(x = mean(gross/1000000)+15 , y =600,label = &#39;mean&#39;),
                                              angle=-90,color = &#39;#C7C8CF&#39;)+
            
  #adding median line and label 
                                                  
   geom_vline(aes(xintercept = median(gross/1000000)), color = &#39;#F9F871&#39; , size = 2,
             linetype = &#39;dotted&#39;)+ 
  geom_text(aes(x = median(gross/1000000)+15 , y =600,label = &#39;median&#39;),
                                              angle=-90, 
                                                  color = &#39;#C7C8CF&#39; ,)+
  
  #adding titles and other theme componenets 
  labs(x = &#39;\nBox Office Gross  mn USD&#39;,
       y = &#39;Count\n&#39;,
       title = &#39;Hollywood relies on the few big ones.&#39; ,
       subtitle = &#39;Distribution of Box Office Gross\n&#39;) +
  scale_colour_solarized(&quot;blue&quot;)+
  scale_x_continuous(expand = c(0,0))+
    scale_y_continuous(expand = c(0,0))+
  #matching the graph to the theme
  theme(
        plot.background = element_rect(fill = &#39;#2B304A&#39;, colour =&#39;#2B304A&#39; ),
        axis.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39; ), 
        axis.text =  element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;) ,
        panel.grid = element_blank() ,
        panel.border = element_blank(),
        plot.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        plot.subtitle = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        panel.background = element_rect(fill = &#39;#2B304A&#39;, color = &#39;#2B304A&#39;) ,
        axis.ticks = element_line(color = &#39;#C7C8CF&#39;),

        
        
        )</code></pre>
<p><img src="/blogs/imdb_rat_files/figure-html/unnamed-chunk-3-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>We get a highly right skewed distribution with very few movies making more than 200mn and average movie, in terms of both median and mean, making below even 100mn. So why do some movies make so much more than others?</p>
<p>We all know the saying that to make you need to spend money, let’s see if that applies to the movie industry. We can plot the box office budget with the gross to see if there is any correlation.</p>
<pre class="r"><code>#calculating correlation 
corr &lt;-
  cor(movies$gross,movies$budget)

#scatter plot of gross vs box office 
movies %&gt;%
  ggplot()+
  geom_point(aes(x = budget/1e6 , y= gross/1e6 ) , color= &#39;#EA8272&#39;)+
  #adding line 
  geom_smooth(aes(x = budget/1e6 , y= gross/1e6 ), method = &#39;lm&#39; ,color = &#39;#F9F871&#39; ) +

  
   #adding titles and other theme componenets 
  labs(y = &#39;Box Office Gross  mn USD \n&#39;,
       x = &#39;\n Movie Budget  mn USD&#39;,
       title = &#39; &#39; ,
       subtitle = &#39; Box Office Gross\n vs Budget&#39;) +
  scale_colour_solarized(&quot;blue&quot;)+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  #matching the graph to the theme
  theme(
        plot.background = element_rect(fill = &#39;#2B304A&#39;, colour =&#39;#2B304A&#39; ),
        axis.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39; ), 
        axis.text =  element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;) ,
       
        panel.grid = element_blank() ,
        panel.border = element_blank(),
        plot.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        plot.subtitle = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        panel.background = element_rect(fill = &#39;#2B304A&#39;, color = &#39;#2B304A&#39;) ,
        axis.ticks = element_line(color = &#39;#C7C8CF&#39;),
)+
  
  ##adding correlation 
    geom_text(aes(x = max(budget/1e6)-50 , y =100),label = paste0(&#39;Correlation: &#39; , round(corr,2)),
    color = &#39;#C7C8CF&#39; ,)</code></pre>
<p><img src="/blogs/imdb_rat_files/figure-html/unnamed-chunk-4-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>Although not strong we do see some positive correlation between budget and box office returns. But to get get a clearer picture let’s divide the budget into three categories: high, low, and medium and see which category has those big blockbusters.</p>
<pre class="r"><code>#defining three catergoes
#low is &lt;50 medium is 51-150 and high is 150+

movies %&gt;% 
  mutate(budget_cat = case_when(
    budget &lt; 5e7 ~ &#39;Low&#39;,
    budget &gt;= 5e7 &amp; budget &lt; 1.5e8 ~ &#39;Medium&#39; ,
    budget &gt;= 1.5e8 ~ &#39;High&#39;
    
  )) %&gt;%
  ggplot(aes(x = budget_cat , y= gross/1e6)) +
  geom_boxplot( color =  &#39;#F9F871&#39;  , fill =  &#39;#EA8272&#39;) + 
  
    #adding titles and other theme componenets 
  labs(y = &#39;Box Office Gross  mn USD \n&#39;,
       x = &#39;\n Movie Budget  Category&#39;,
       title = &#39; &#39; ,
       subtitle = &#39; Box Office Gross\n vs Budget&#39;) +
  scale_colour_solarized(&quot;blue&quot;)+
  scale_x_discrete(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  #matching the graph to the theme
  theme(
        plot.background = element_rect(fill = &#39;#2B304A&#39;, colour =&#39;#2B304A&#39; ),
        axis.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39; ), 
        axis.text =  element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;) ,
        panel.grid = element_blank() ,
        panel.border = element_blank(),
        plot.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        plot.subtitle = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        panel.background = element_rect(fill = &#39;#2B304A&#39;, color = &#39;#2B304A&#39;) ,
        axis.ticks = element_line(color = &#39;#C7C8CF&#39;),
)</code></pre>
<p><img src="/blogs/imdb_rat_files/figure-html/unnamed-chunk-5-1.png" width="1056" style="display: block; margin: auto;" />
We see that the distribution of box office gross significantly varies between the low and high budget categories,so this indicates that spending money on making your movie lets you make those extra dollars at the box office. However, another metric, potentially a more important one, is actually looking at the return on investment, so lets create a variable called <code>roi</code> defined as % return on the budget.</p>
<pre class="r"><code>movies %&gt;% 
  mutate(roi = round(((gross - budget)/budget)*100 , 2)) %&gt;%
  mutate(budget_cat = case_when(
    budget &lt; 5e7 ~ &#39;Low&#39;,
    budget &gt;= 5e7 &amp; budget &lt; 1.5e8 ~ &#39;Medium&#39; ,
    budget &gt;= 1.5e8 ~ &#39;High&#39;
    
  ))%&gt;%
   ggplot(aes( x = budget_cat , y= roi)) +
  geom_boxplot( color =  &#39;#F9F871&#39;  , fill =  &#39;#EA8272&#39;) + 
  
    #adding titles and other theme componenets 
  labs(y = &#39;ROI(%) \n&#39;,
       x = &#39;\n Movie Budget  Category&#39;,
       title = &#39; &#39; ,
       subtitle = &#39; Box Office ROI \n vs Budget Category&#39;) +
  scale_colour_solarized(&quot;blue&quot;)+
  scale_x_discrete(expand = c(0,0))+
  #limiting the y axis to avoid shrinking y axis due to out liers
  scale_y_continuous(expand = c(0,0) , limits = c(0,400))+
  #matching the graph to the theme
  theme(
        plot.background = element_rect(fill = &#39;#2B304A&#39;, colour =&#39;#2B304A&#39; ),
        axis.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39; ), 
        axis.text =  element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;) ,
        panel.grid = element_blank() ,
        panel.border = element_blank(),
        plot.title = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        plot.subtitle = element_text(color = &#39;#C7C8CF&#39; , face = &#39;bold&#39;),
        panel.background = element_rect(fill = &#39;#2B304A&#39;, color = &#39;#2B304A&#39;) ,
        axis.ticks = element_line(color = &#39;#C7C8CF&#39;),
)</code></pre>
<p><img src="/blogs/imdb_rat_files/figure-html/unnamed-chunk-6-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>Now we see that the picture changes completely and the high budget movies don’t see me to be as lucrative any more. The mean ROI of the low budget category is not the highest but there still seems to significant overlap between the high and low budget categories.</p>
</div>
